cmake_minimum_required(VERSION 3.16)
project(federated_learning)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_pytest REQUIRED)
install(PROGRAMS nodes/federated_learning_node.py DESTINATION lib/${PROJECT_NAME} RENAME federated_learning_node)
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  ament_add_pytest_test(test_federated_learning tests/test_federated_learning.py)
endif()
ament_package()
