cmake_minimum_required(VERSION 3.16)
project(zero_knowledge_sharing)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_pytest REQUIRED)
install(PROGRAMS nodes/zero_knowledge_sharing_node.py DESTINATION lib/${PROJECT_NAME} RENAME zero_knowledge_sharing_node)
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  ament_add_pytest_test(test_zero_knowledge_sharing tests/test_zero_knowledge_sharing.py)
endif()
ament_package()
