cmake_minimum_required(VERSION 3.16)
project(verification)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_pytest REQUIRED)
install(PROGRAMS nodes/verification_node.py DESTINATION lib/${PROJECT_NAME} RENAME verification_node)
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  ament_add_pytest_test(test_verification tests/test_verification.py)
endif()
ament_package()
