apiVersion: v1
kind: Service
metadata:
  name: ancile-aeris-dashboard
  namespace: ancile-aeris
spec:
  type: NodePort
  selector:
    app: ancile-aeris-core
  ports:
    - name: streamlit
      port: 8501
      targetPort: 8501
      nodePort: 30501
