cmake_minimum_required(VERSION 3.16)
project(cognitive_ew)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_pytest REQUIRED)
install(PROGRAMS nodes/cognitive_ew_node.py DESTINATION lib/${PROJECT_NAME} RENAME cognitive_ew_node)
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  ament_add_pytest_test(test_cognitive_ew tests/test_cognitive_ew.py)
endif()
ament_package()
