cmake_minimum_required(VERSION 3.16)
project(causal_xai)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_pytest REQUIRED)
install(PROGRAMS nodes/causal_xai_node.py DESTINATION lib/${PROJECT_NAME} RENAME causal_xai_node)
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  ament_add_pytest_test(test_causal_xai tests/test_causal_xai.py)
endif()
ament_package()
